### ISSUE TITLE
Support deploy keys

### ISSUE THREAD

**Issue by razor-x** [jirutka/rake-jekyll#6]
I've made some updates to my original Rake task. In particular, I've switched to using deploy keys over tokens. Here is the behavior I imagine should be implemented here.

1) Check for `.deploy_key`, if found use the deploy key method. (Add an option to set the name of the `deploy_key` file to use). This method needs to use git over ssh not https.
2) Otherwise fall back to token method.

See here for the relevant changes in `Rakefile`: https://github.com/razor-x/jekyll-and-zurb/compare/15465d21578aa0af20837f3ec7d228c6efeffe6f...master

Note in particular that the deploy key should never be allowed to be committed to the build (e.g. don't leave it up to the user to add it to some ignore file).

Also updated README instructions: https://github.com/razor-x/jekyll-and-zurb#automatic-publishing-to-github-pages-with-travis-ci

**Comment by rberger** [comment]
This may not work for Organization and User pages:
Seems Github is saying "Don't use deploy keys"
https://help.github.com/articles/troubleshooting-github-pages-build-failures/#deploy-key-used-for-push

**Comment by razor-x** [comment]
That's odd, I have tested this method for an organization repo both normal and for the special .io repo name. See for example https://github.com/agony-unleashed/agony-unleashed.github.io

**Comment by rberger** [comment]
I'm a gh-pages/jekyll noob, I just saw that instruction from Github in the Github help pages while I'm trying to figure out why my repo (https://github.com/mistsys/mistsys.github.io)  doesn't work. Its built with https://github.com/asciidoctor/jekyll-asciidoc-quickstart which uses rake-jekyll.

I noticed that in your example https://github.com/agony-unleashed/agony-unleashed.github.io you have the markdown in the source branch and the rendered html in the master. I was under the impression that the source should be in master and the rendered in gh-pages. Am I just mixed up?

Thanks for any help you may have.

**Comment by razor-x** [comment]
@rberger Take a look at https://pages.github.com. gh-pages branch is for all repos except the special .io one  that can exist for a user or org. Those special repos serve off of the master branch.

**Comment by rberger** [comment]
Thanks for the tip! That is so much clearer than the github help pages. Also means that the asciidoctor quick start (at least the docs) needs to be modified to properly deploy to user/organization pages.

Thanks

**Comment by sandermak** [comment]
@rberger I was running into the same issue with asciidoctor/jekyll-asciidoc-quickstart

I solved it by creating a `source` branch that contains the quickstart template, and changing the Rakefile to deploy to the master branch:

```
Rake::Jekyll::GitDeployTask.new(:deploy) do |t|
    t.deploy_branch = 'master'
end
```

**Comment by razor-x** [comment]
@rberger This will auto-select the correct branch:

``` ruby
t.deploy_branch = -> {
  t.remote_url.match(/github\.io\.git$/) ? 'master' : 'gh-pages'
}
```

This will use the ssh url if you want to use deply keys:

``` ruby

t.remote_url = -> {
  %x(git config remote.origin.url)
  .gsub(%r{^git://}, 'git@')
  .sub(%r{/}, ':').strip
}
```

**Comment by jirutka** [comment]
@rberger I’ve implemented support for SSH keys in 90445790e9e6a56f041cc0f18a5256346d7f114a. Please try it and let me know if it’s suitable for you.

**Comment by razor-x** [comment]
I tried using this here https://github.com/razor-x/jekyll-and-zurb/commit/e2522d06c5afd06cb39972116e98ce4076802801, but I had to revert and keep the ssh-agent stuff, https://github.com/razor-x/jekyll-and-zurb/commit/c59cf96f773659f1fca5957a1f853f22f14a3aa4.

Here is the failed Travis build: https://travis-ci.org/razor-x/jekyll-and-zurb/builds/68561632, in particular it fails with:

```
$ bundle exec rake travis

git clone 'git@github.com:razor-x/jekyll-and-zurb.git' .

Cloning into '.'...

Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.
```

**Comment by razor-x** [comment]
I think the problem here is simply that when using the ssh address `git@github.com:user/repo.git` to clone, you need a valid public key, which doesn't exist normally in the Travis environment.

**Comment by jirutka** [comment]
Nope, the problem is that Travis uses very old version of git that doesn’t support `GIT_SSH_COMMAND` yet (Ubuntu :angry:). So I have to find another solution.

**Comment by jirutka** [comment]
Fixed in 1f298b2ddb36fd16b92a6f9e40729464a3114656. I’ve tested it with Travis and it works now.

**Comment by jirutka** [comment]
@razor-x, please let me know if it works for you. I’ll publish 1.1.0 after that.

**Comment by razor-x** [comment]
I'm trying it now here:
- Working with ssh-agent: https://travis-ci.org/rxfork/jekyll-and-zurb/builds/68737281
- Failing when I remove it: https://travis-ci.org/rxfork/jekyll-and-zurb/builds/68737394

I thought maybe I needed to keep only `sh 'chmod 600 .deploy_key'`, but it still fails with that.
I know the Travis docs say to use the ssh-agent, but if you have it working I'm not sure why mine would fail.

**Comment by jirutka** [comment]
I think that the difference is that you don’t have a public key in your repository. I’ve commited both encrypted private key and unencrypted public key.

**Comment by razor-x** [comment]
Hmm, I'm not sure how that would cause the issue. I just tested your suggestion by adding `.deploy_key.pub` and it still fails the same way: https://travis-ci.org/rxfork/jekyll-and-zurb/builds/68738195

**Comment by jirutka** [comment]
Okay, I see the problem… Replace `gem 'rake-jekyll', '~> 1.0.3', github: 'jirutka/rake-jekyll'` with `gem 'rake-jekyll', github: 'jirutka/rake-jekyll', ref: '1f298b2'` in your Gemfile, run `bundle install` and commit changes in both Gemfile and Gemfile.lock. ;)

**Comment by razor-x** [comment]
The branch that is building from already uses the gem from GitHub: https://github.com/rxfork/jekyll-and-zurb/blob/70099a0cbdcb08c6fb97c663232f16e19b6fd081/Gemfile.lock#L1-L3

**Comment by razor-x** [comment]
I tried updating it anyway to match, but still failing:
- https://github.com/rxfork/jekyll-and-zurb/blob/rake-refactor/Gemfile#L5
- https://travis-ci.org/rxfork/jekyll-and-zurb/builds/68740460

**Comment by razor-x** [comment]
Any particular reason you don't want to just use something like

``` bash
eval $(ssh-agent)
chmod 600 "$SSH_PRIVATE_KEY"
ssh-add "$SSH_PRIVATE_KEY"
```

**Comment by razor-x** [comment]
Would love to get v1.1.0 out. Do you have an example of a repo where this is working? Maybe I can compare and try and see why I can only get it to work via ssh-agent.

If you have tested it and it's on my end only, don't let that hold up v1.1.0. I can still update to v1.1.0  and just use the ssh-agent workaround until I work out the issue.

**Comment by jirutka** [comment]
> Do you have an example of a repo where this is working?

Yeah, I’ve just created it in the branch [test-deploy-key](https://github.com/jirutka/rake-jekyll/tree/test-deploy-key). And [here](https://travis-ci.org/jirutka/rake-jekyll/builds/73645224) is a successful build on Travis.

**Comment by jirutka** [comment]
@razor-x Have you looked at it, any ideas why it doesn’t work for you?

**Comment by razor-x** [comment]
@jirutka Yes, sorry. I updated to 1.1.0 and I have it working without ssh-agent now. Not 100% sure what the issue was before.

**Comment by jirutka** [comment]
Great, I’m glad that it works for you! :smile_cat:

BTW, the reason I didn’t want to use ssh-agent is that it may affect some other tasks outside of this one. This may not be an issue in practice, but… The solution with `GIT_SSH` variable is IMHO cleaner and doesn’t have any side-effects outside of the rake process.

**Comment by razor-x** [comment]
@jirutka That's smart, I'm glad you found that alternative as I didn't really like using ssh-agent either and you're right about possible side effects (it was just what the Travis docs said to use).
